"""
Table catalog: maps BNM MHS table IDs to (slug, domain, full_title).
slug is used as the DuckDB table name suffix.
"""

CATALOG = {
    # ── Section 1: Monetary & Banking ─────────────────────────────────────────
    "1.1":      ("reserve_money",                         "monetary",  "Reserve Money"),
    "1.2":      ("currency_circulation_by_denom",         "monetary",  "Currency in Circulation by Denomination"),
    "1.3":      ("monetary_aggregates",                   "monetary",  "Monetary Aggregates: M1, M2 and M3"),
    "1.3.1":    ("broad_money_m3",                        "monetary",  "Broad Money, M3"),
    "1.3.2":    ("factors_affecting_m3",                  "monetary",  "Factors Affecting M3"),
    "1.4":      ("bnm_assets",                            "monetary",  "BNM: Statement of Assets"),
    "1.5":      ("bnm_capital_liabilities",               "monetary",  "BNM: Statement of Capital and Liabilities"),
    "1.5.1":    ("bnm_capital_liabilities_prev",          "monetary",  "BNM: Statement of Capital and Liabilities (prev)"),
    "1.6":      ("bnm_special_funds",                     "monetary",  "BNM Special Funds"),
    "1.7":      ("banking_assets",                        "banking",   "Banking System: Statement of Assets"),
    "1.7a":     ("banking_assets_prev",                   "banking",   "Banking System: Statement of Assets (prev)"),
    "1.7.1":    ("islamic_banking_assets",                "banking",   "Islamic Banking System: Statement of Assets"),
    "1.7.2":    ("comm_islamic_banks_assets",             "banking",   "Commercial & Islamic Banks: Statement of Assets"),
    "1.7.2.1":  ("comm_islamic_banks_assets_prev",        "banking",   "Commercial & Islamic Banks: Assets (prev)"),
    "1.7.3":    ("comm_islamic_dom_foreign_assets",       "banking",   "Commercial & Islamic Banks: Domestic & Foreign Assets"),
    "1.7.3.1":  ("comm_islamic_dom_foreign_assets_prev",  "banking",   "Commercial & Islamic Banks: Domestic & Foreign Assets (prev)"),
    "1.7.4":    ("investment_banks_assets",               "banking",   "Investment Banks: Statement of Assets"),
    "1.7.5":    ("finance_cos_assets",                    "banking",   "Finance Companies: Statement of Assets"),
    "1.8":      ("life_general_insurance_assets",         "insurance", "Life and General Insurance Funds: Statement of Assets"),
    "1.9":      ("banking_capital_liabilities",           "banking",   "Banking System: Statement of Capital and Liabilities"),
    "1.9a":     ("banking_capital_liabilities_prev",      "banking",   "Banking System: Capital and Liabilities (prev)"),
    "1.9.1":    ("islamic_banking_capital_liabilities",   "banking",   "Islamic Banking System: Statement of Capital & Liabilities"),
    "1.9.2":    ("comm_islamic_banks_liabilities",        "banking",   "Commercial & Islamic Banks: Statement of Liabilities"),
    "1.9.2.1":  ("comm_islamic_banks_liab_prev",          "banking",   "Commercial & Islamic Banks: Liabilities (prev)"),
    "1.9.3":    ("comm_islamic_dom_foreign_liab",         "banking",   "Commercial & Islamic Banks: Domestic & Foreign Liabilities"),
    "1.9.3.1":  ("comm_islamic_dom_foreign_liab_prev",    "banking",   "Commercial & Islamic Banks: Domestic & Foreign Liabilities (prev)"),
    "1.9.4":    ("investment_banks_liabilities",          "banking",   "Investment Banks: Statement of Liabilities"),
    "1.9.5":    ("finance_cos_liabilities",               "banking",   "Finance Companies: Statement of Liabilities"),
    "1.9.5.1":  ("finance_cos_assets_liab_prev",          "banking",   "Finance Companies: Assets and Liabilities (prev)"),
    "1.9.6":    ("banking_external_assets_liab",          "banking",   "Banking System: External Assets and Liabilities"),
    "1.10":     ("loans_applied_by_purpose",              "credit",    "Banking System: Loan/Financing Applied by Purpose"),
    "1.10a":    ("loans_applied_by_purpose_prev",         "credit",    "Banking System: Loans Applied by Purpose (prev)"),
    "1.11":     ("loans_applied_by_sector",               "credit",    "Banking System: Loan/Financing Applied by Sector"),
    "1.11a":    ("loans_applied_by_sector_prev",          "credit",    "Banking System: Loans Applied by Sector (prev)"),
    "1.11.1":   ("loans_applied_by_type",                 "credit",    "Banking System: Loan/Financing Applied by Type"),
    "1.12":     ("loans_approved",                        "credit",    "Banking System: Loan/Financing Approved"),
    "1.12a":    ("loans_approved_by_purpose_prev",        "credit",    "Banking System: Loans Approved by Purpose (prev)"),
    "1.13":     ("loans_approved_by_sector",              "credit",    "Banking System: Loan/Financing Approved by Sector"),
    "1.13a":    ("loans_approved_by_sector_prev",         "credit",    "Banking System: Loans Approved by Sector (prev)"),
    "1.13.1":   ("loans_approved_by_sector_prev2",        "credit",    "Banking System: Loans Approved by Sector (prev2)"),
    "1.13.2":   ("loans_approved_by_type",                "credit",    "Banking System: Loan/Financing Approved by Type"),
    "1.14":     ("loans_disbursed_by_purpose",            "credit",    "Banking System: Loan/Financing Disbursed by Purpose"),
    "1.14a":    ("loans_disbursed_by_purpose_prev",       "credit",    "Banking System: Loans Disbursed by Purpose (prev)"),
    "1.15":     ("loans_disbursed_by_sector",             "credit",    "Banking System: Loan/Financing Disbursed by Sector"),
    "1.15a":    ("loans_disbursed_by_sector_prev",        "credit",    "Banking System: Loans Disbursed by Sector (prev)"),
    "1.15.1":   ("loans_disbursed_by_sector_prev2",       "credit",    "Banking System: Loans Disbursed by Sectors (prev2)"),
    "1.15.2":   ("loans_disbursed_by_type",               "credit",    "Banking System: Loan/Financing Disbursed by Type"),
    "1.16":     ("loans_repaid_by_purpose",               "credit",    "Banking System: Loan/Financing Repaid by Purpose"),
    "1.16a":    ("loans_repaid_by_purpose_prev",          "credit",    "Banking System: Loans Repaid by Purpose (prev)"),
    "1.17":     ("loans_repaid_by_sector",                "credit",    "Banking System: Loan/Financing Repaid by Sector"),
    "1.17a":    ("loans_repaid_by_sector_prev",           "credit",    "Banking System: Loans Repaid by Sector (prev)"),
    "1.17.1":   ("loans_repaid_by_sector_prev2",          "credit",    "Banking System: Loans Repaid by Sectors (prev2)"),
    "1.17.2":   ("loans_repaid_by_type",                  "credit",    "Banking System: Loan/Financing Repaid by Type"),
    "1.18":     ("loans_by_type",                         "credit",    "Banking System: Loan/Financing by Type"),
    "1.18.1":   ("islamic_financing_by_type",             "credit",    "Islamic Banking: Financing by Type"),
    "1.18.2":   ("islamic_financing_by_shariah",          "credit",    "Islamic Banking: Financing by Shariah Contract"),
    "1.18.3":   ("loans_by_location",                     "credit",    "Banking System: Loan/Financing by Location"),
    "1.18a":    ("loans_by_type_prev",                    "credit",    "Banking System: Classification of Loans by Type (prev)"),
    "1.18.1a":  ("islamic_financing_by_type_prev",        "credit",    "Islamic Banking: Financing by Type (prev)"),
    "1.18.2a":  ("islamic_financing_by_concept_prev",     "credit",    "Islamic Banking: Financing by Concept (prev)"),
    "1.19":     ("loans_by_purpose",                      "credit",    "Banking System: Loan/Financing by Purpose"),
    "1.19a":    ("loans_by_purpose_prev",                 "credit",    "Banking System: Loans by Purpose (prev)"),
    "1.19b":    ("loans_by_purpose_prev2",                "credit",    "Banking System: Loans by Purpose (prev2)"),
    "1.19c":    ("loans_by_purpose_prev3",                "credit",    "Banking System: Loan/Financing by Purpose (prev3)"),
    "1.19.1":   ("islamic_financing_purpose_sector",      "credit",    "Islamic Banking: Financing by Purpose and Sectors"),
    "1.19.1a":  ("islamic_financing_purpose_sector_prev", "credit",    "Islamic Banking: Financing by Purpose and Sectors (prev)"),
    "1.19.2":   ("islamic_loans_purpose_sector_prev",     "credit",    "Islamic Banking: Loans by Purpose and Sector (prev)"),
    "1.19.3":   ("islamic_loans_type_sector_prev",        "credit",    "Islamic Banking: Loans by Type and Sector (prev)"),
    "1.19.4":   ("comm_islamic_loans_by_purpose",         "credit",    "Commercial & Islamic Banks: Loans/Financing by Purpose"),
    "1.19.5":   ("investment_banks_loans_by_purpose",     "credit",    "Investment Banks: Classification of Loans by Purpose"),
    "1.19.6":   ("household_loans_by_purpose",            "credit",    "Banking System: Household Loan/Financing by Purpose"),
    "1.19.6a":  ("household_loans_by_purpose_prev",       "credit",    "Banking System: Household Loan/Financing by Purpose (prev)"),
    "1.20":     ("loans_by_sector",                       "credit",    "Banking System: Loan/Financing by Sector"),
    "1.20a":    ("loans_by_sector_prev",                  "credit",    "Banking System: Loans by Sector (prev)"),
    "1.20b":    ("loans_by_sector_prev2",                 "credit",    "Banking System: Loans by Sector (prev2)"),
    "1.20.1":   ("comm_islamic_loans_by_sector",          "credit",    "Commercial & Islamic Banks: Loans/Financing by Sector"),
    "1.20.2":   ("comm_islamic_loans_by_sector_prev",     "credit",    "Commercial & Islamic Banks: Loans by Sector (prev)"),
    "1.20.3":   ("investment_banks_loans_by_sector",      "credit",    "Investment Banks: Classification of Loans by Sector"),
    "1.20.4":   ("investment_banks_loans_by_sector_prev", "credit",    "Merchant Banks: Loans by Sector (prev)"),
    "1.20.5":   ("finance_cos_loans_by_sector_prev",      "credit",    "Finance Companies: Loans by Sector (prev)"),
    "1.20.6":   ("finance_cos_loans_by_sector_hist",      "credit",    "Finance Companies: Loans by Sector (historical)"),
    "1.21":     ("loans_mfrs9_stages_provisions",         "credit",    "Banking System: Loans by MFRS 9 Stages and Provisions"),
    "1.21a":    ("npl_impaired_provisions_prev",          "credit",    "Banking System: NPL/Impaired Loans and Provisions (prev)"),
    "1.21b":    ("impaired_loans_provisions_prev",        "credit",    "Banking System: Impaired Loans and Provisions (prev)"),
    "1.21c":    ("impaired_loans_provisions_prev2",       "credit",    "Banking System: Impaired Loans and Provisions (prev2)"),
    "1.21d":    ("impaired_loans_provisions_prev3",       "credit",    "Banking System: Impaired Loans and Provisions (prev3)"),
    "1.21.1":   ("islamic_financing_mfrs9_stages",        "credit",    "Islamic Banking: Financing by MFRS 9 Stages and Provisions"),
    "1.21.1a":  ("islamic_npl_impaired_prev",             "credit",    "Islamic Banking: NPL/Impaired and Provisions (prev)"),
    "1.21.1b":  ("islamic_impaired_provisions_prev",      "credit",    "Islamic Banking: Impaired Financing and Provisions (prev)"),
    "1.21.1c":  ("islamic_impaired_provisions_prev2",     "credit",    "Islamic Banking: Impaired Financing and Provisions (prev2)"),
    "1.21.1d":  ("islamic_impaired_provisions_prev3",     "credit",    "Islamic Banking: Impaired Financing and Provisions (prev3)"),
    "1.21.2":   ("comm_islamic_npl_impaired",             "credit",    "Commercial & Islamic Banks: NPL/Impaired Loans"),
    "1.21.2a":  ("comm_islamic_impaired_prev",            "credit",    "Commercial & Islamic Banks: Impaired Loans (prev)"),
    "1.21.2b":  ("comm_islamic_impaired_prev2",           "credit",    "Commercial & Islamic Banks: Impaired Loans (prev2)"),
    "1.21.3":   ("investment_banks_npl_impaired",         "credit",    "Investment Banks: NPL/Impaired Loans"),
    "1.21.3a":  ("investment_banks_impaired_prev",        "credit",    "Investment Banks: Impaired Loans (prev)"),
    "1.21.3b":  ("investment_banks_impaired_prev2",       "credit",    "Investment Banks: Impaired Loans (prev2)"),
    "1.21.4":   ("finance_cos_npl_provisions",            "credit",    "Finance Companies: Loan Provisions and NPL"),
    "1.22":     ("impaired_loans_by_purpose",             "credit",    "Banking System: Impaired Loan/Financing by Purpose"),
    "1.22a":    ("npl_by_purpose_prev",                   "credit",    "Banking System: NPL/Impaired Loans by Purpose (prev)"),
    "1.22b":    ("npl_by_purpose_prev2",                  "credit",    "Banking System: NPL/Impaired Loans by Purpose (prev2)"),
    "1.22c":    ("impaired_loans_by_purpose_prev",        "credit",    "Banking System: Impaired Loans by Purpose (prev)"),
    "1.22.1":   ("comm_islamic_npl_by_purpose",           "credit",    "Commercial & Islamic Banks: NPL by Purpose"),
    "1.22.2":   ("investment_banks_npl_by_purpose",       "credit",    "Investment Banks: NPL/Impaired Loans by Purpose"),
    "1.23":     ("impaired_loans_by_sector",              "credit",    "Banking System: Impaired Loan/Financing by Sector"),
    "1.23a":    ("npl_by_sector_prev",                    "credit",    "Banking System: NPL/Impaired Loans by Sector (prev)"),
    "1.23b":    ("npl_by_sector_prev2",                   "credit",    "Banking System: NPL/Impaired Loans by Sector (prev2)"),
    "1.23.1":   ("comm_islamic_npl_by_sector",            "credit",    "Commercial & Islamic Banks: NPL by Sector"),
    "1.23.2":   ("comm_islamic_npl_by_sector_prev",       "credit",    "Commercial & Islamic Banks: NPL by Sector (prev)"),
    "1.23.3":   ("investment_banks_npl_by_sector",        "credit",    "Investment Banks: NPL/Impaired Loans by Sector"),
    "1.23.4":   ("investment_banks_npl_by_sector_prev",   "credit",    "Merchant Banks: NPL by Sector (prev)"),
    "1.23.5":   ("finance_cos_npl_by_sector",             "credit",    "Finance Companies: Non-Performing Loans by Sector"),
    "1.23.6":   ("impaired_loans_by_type",                "credit",    "Banking System: Impaired Loan/Financing by Type"),
    "1.24":     ("total_deposits_by_type",                "deposits",  "Banking System: Total Deposits by Type"),
    "1.24.1":   ("islamic_deposits_by_type",              "deposits",  "Islamic Banking: Deposits by Type"),
    "1.24.2":   ("islamic_deposits_by_type_holder",       "deposits",  "Islamic Banking: Deposits by Type & Holder"),
    "1.24.3":   ("islamic_deposits_by_type_holder_prev",  "deposits",  "Islamic Banking: Deposits by Type and Holder (prev)"),
    "1.25":     ("total_deposits_by_holder",              "deposits",  "Banking System: Total Deposits by Holder"),
    "1.25.1":   ("demand_deposits_by_holder",             "deposits",  "Banking System: Demand Deposits by Holder"),
    "1.25.2":   ("savings_fixed_deposits_by_holder",      "deposits",  "Banking System: Savings and Fixed Deposits by Holder"),
    "1.25.3":   ("repo_by_holder",                        "deposits",  "Banking System: Repurchase Agreements by Holder"),
    "1.25.4":   ("nids_by_holder",                        "deposits",  "Banking System: NIDs by Holder"),
    "1.25.5":   ("fx_other_deposits_by_holder",           "deposits",  "Banking System: Foreign Currency and Other Deposits by Holder"),
    "1.25.6":   ("fixed_deposits_by_maturity",            "deposits",  "Banking System: Fixed Deposits by Original Maturity"),
    "1.26":     ("statutory_reserve_liquidity",           "banking",   "Statutory Reserve Requirement and Liquidity Ratio"),
    "1.27":     ("statutory_reserve_liquid_asset",        "banking",   "Statutory Reserve and Liquid Asset Requirement"),
    "1.28":     ("new_liquidity_framework",               "banking",   "New Liquidity Framework"),
    "1.28a":    ("liquidity_coverage_ratio",              "banking",   "Liquidity Coverage Ratio"),
    "1.29":     ("banking_capital_components",            "banking",   "Banking System: Constituents of Capital"),
    "1.29a":    ("banking_capital_components_v2",         "banking",   "Banking System: Constituents of Capital (v2)"),
    "1.29b":    ("banking_capital_components_prev",       "banking",   "Banking System: Constituents of Capital (prev)"),
    "1.29.1":   ("islamic_banking_capital",               "banking",   "Islamic Banking System: Constituents of Capital"),
    "1.29.1a":  ("islamic_banking_capital_v2",            "banking",   "Islamic Banking System: Constituents of Capital (v2)"),
    "1.29.2":   ("comm_islamic_banks_capital",            "banking",   "Commercial & Islamic Banks: Constituents of Capital"),
    "1.29.2a":  ("comm_islamic_banks_capital_prev",       "banking",   "Commercial & Islamic Banks: Capital (prev)"),
    "1.29.3":   ("finance_cos_capital",                   "banking",   "Finance Companies: Constituents of Capital"),
    "1.29.4":   ("investment_banks_capital",              "banking",   "Investment Banks: Constituents of Capital"),
    "1.29.4a":  ("investment_banks_capital_prev",         "banking",   "Investment Banks: Constituents of Capital (prev)"),
    "1.30":     ("credit_card_operations",                "payments",  "Credit Card Operations in Malaysia"),
    "1.30.1":   ("debit_card_transactions",               "payments",  "Debit Card Transactions"),
    "1.31":     ("loan_fund_ratio_liquidity",             "banking",   "Banking System: Loan to Fund Ratio and Liquidity"),
    "1.32":     ("islamic_investment_account",            "banking",   "Islamic Banking: Total Investment Account by Type and Holder"),
    "1.32.1":   ("islamic_ia_assets",                     "banking",   "Islamic Banking: Assets funded through Investment Account"),
    "1.32.2":   ("islamic_ia_financing_by_type",          "banking",   "Islamic Banking: Financing through Investment Account by Type"),
    "1.32.3":   ("islamic_ia_financing_by_concept",       "banking",   "Islamic Banking: Financing through Investment Account by Concept"),
    "1.32.4":   ("islamic_ia_financing_purpose_sector",   "banking",   "Islamic Banking: Financing through Investment Account by Purpose"),
    "1.32.5":   ("islamic_ia_by_maturity",                "banking",   "Islamic Banking: Total Investment Account by Original Maturity"),
    "1.33":     ("sme_loans_by_sector",                   "sme",       "Financial Institution: SME Loan/Financing by Sector"),
    "1.33.1":   ("sme_loans_applied_by_sector",           "sme",       "Financial Institution: SME Loan/Financing Applied by Sector"),
    "1.33.2":   ("sme_loans_approved_by_sector",          "sme",       "Financial Institution: SME Loan/Financing Approved by Sector"),
    "1.33.3":   ("sme_loans_disbursed_by_sector",         "sme",       "Financial Institution: SME Loan/Financing Disbursed by Sector"),
    "1.33.4":   ("sme_loans_repaid_by_sector",            "sme",       "Financial Institution: SME Loan/Financing Repaid by Sector"),
    "1.33.5":   ("sme_impaired_loans_by_sector",          "sme",       "Financial Institution: Impaired SME Loan/Financing by Sector"),
    "1.34":     ("sme_loans_by_purpose",                  "sme",       "Financial Institutions: SME Loan/Financing by Purpose"),
    "1.35":     ("sme_loans_by_size",                     "sme",       "Financial Institution: SME Loan/Financing by SME Size"),
    "1.35.1":   ("sme_loans_applied_approved_by_size",    "sme",       "Financial Institution: SME Loans Applied and Approved by Size"),
    "1.35.2":   ("sme_loans_disbursed_repaid_by_size",    "sme",       "Financial Institution: SME Loans Disbursed and Repaid by Size"),
    "1.35.3":   ("sme_impaired_loans_by_size",            "sme",       "Financial Institution: Impaired SME Loans by Size"),
    "1.36":     ("sme_loans_by_loan_size",                "sme",       "Financial Institution: SME Loan/Financing by Loan Size"),
    # ── Section 2: Rates & Capital Markets ────────────────────────────────────
    "2.1":      ("interest_rates_banking",                "rates",     "Interest Rates: Banking Institutions"),
    "2.1a":     ("interest_rates_banking_prev",           "rates",     "Interest Rates: Banking Institutions (prev)"),
    "2.2":      ("islamic_financing_profit_rates",        "rates",     "Islamic Banking: Financing and Profit Rates"),
    "2.2a":     ("islamic_financing_profit_rates_prev",   "rates",     "Islamic Banking: Financing and Profit Rates (prev)"),
    "2.3":      ("interbank_money_market_rates",          "rates",     "Interest Rates: Interbank Money Market"),
    "2.4":      ("treasury_bills_bnm_bills_rates",        "rates",     "Interest Rates: Treasury Bills and Bank Negara Bills"),
    "2.4.1":    ("tbills_mgs_tender_results",             "rates",     "Treasury Bills, MGS and Khazanah Bonds: Tender Results"),
    "2.5":      ("mgs_indicative_yield",                  "rates",     "Market Indicative Yield: Malaysian Government Securities"),
    "2.6":      ("exchange_rates_myr",                    "fx",        "Exchange Rates: Malaysian Ringgit"),
    "2.6.1":    ("exchange_rates_myr_daily",              "fx",        "Exchange Rates: Malaysian Ringgit (Daily)"),
    "2.7":      ("interbank_money_market_volume",         "markets",   "Volume of Transaction in Interbank Money Market"),
    "2.8":      ("kl_fx_market_volume",                   "markets",   "Volume of Interbank Transactions in KL FX Market"),
    "2.9":      ("capital_market_public_sector",          "markets",   "Funds Raised in Capital Market (by Public Sector)"),
    "2.10":     ("capital_market_private_sector",         "markets",   "Funds Raised in Capital Market (by Private Sector)"),
    "2.11":     ("corporate_bond_sukuk_new_issues",       "markets",   "New Issues of Corporate Bond and/or Sukuk"),
    "2.14":     ("money_market_turnover",                 "markets",   "Turnover of Conventional and Islamic Money Market"),
    "2.15":     ("derivatives_turnover",                  "markets",   "Turnover of Derivatives Transactions"),
    "2.16":     ("debt_securities_sukuk_turnover",        "markets",   "Turnover of Debt Securities and Sukuk"),
    "2.17":     ("fx_market_turnover",                    "markets",   "Turnover of Foreign Currency Market Transactions"),
    "2.18":     ("credit_to_private_sector",              "credit",    "Credit to the Private Non-Financial Sector"),
    "2.18a":    ("net_financing_banking_dfi_cb_prev",     "credit",    "Net Financing through Banking, DFIs and Corporate Bonds (prev)"),
    # ── Section 3: Government & External ──────────────────────────────────────
    "3.1":      ("federal_govt_finance",                  "fiscal",    "Federal Government Finance"),
    "3.1.1":    ("federal_govt_revenue",                  "fiscal",    "Federal Government Revenue"),
    "3.1.2":    ("federal_govt_operating_expenditure",    "fiscal",    "Federal Government Operating Expenditure by Object"),
    "3.1.3":    ("federal_govt_development_expenditure",  "fiscal",    "Federal Government Development Expenditure"),
    "3.1.4":    ("federal_govt_debt_by_maturity",         "fiscal",    "Federal Government Debt by Remaining Maturity"),
    "3.1.5":    ("federal_govt_domestic_debt_by_holder",  "fiscal",    "Federal Government Domestic Debt by Holder"),
    "3.1.6":    ("federal_govt_debt_currency_maturity",   "fiscal",    "Federal Government Debt by Currency and Remaining Maturity"),
    "3.2":      ("rentas_foreign_holdings",               "fiscal",    "RENTAS: Foreign Holdings in Debt Securities and Sukuk"),
    "3.5.12a":  ("labour_market_financial_sector",        "labour",    "Labour Market Indicators for the Financial Services Sector"),
    "3.5.14":   ("cheques_statistics",                    "payments",  "Selected Statistics on Cheques Cleared and Returned"),
    "3.5.14a":  ("dishonoured_cheques_prev",              "payments",  "Selected Statistics on Dishonoured Cheques (prev)"),
    "3.6.7":    ("gross_imports_by_economic_function",    "trade",     "Gross Imports by Economic Function"),
    "3.6.19":   ("banking_cross_border_position",         "banking",   "Banking System: Cross-Border Position vs Non-Resident"),
    "3.7":      ("external_debt",                         "external",  "External Debt"),
    "3.8":      ("external_reserves",                     "external",  "External Reserves"),
    # ── Section 4: Insurance & Takaful ────────────────────────────────────────
    "4.1":      ("life_general_insurance_takaful_assets", "insurance", "Life/General Insurance and Takaful Funds: Statement of Assets"),
    "4.2":      ("insurance_assets_liabilities",          "insurance", "Insurance: Assets and Liabilities"),
    "4.3":      ("takaful_assets_liabilities",            "takaful",   "Takaful: Assets and Liabilities"),
    "4.4":      ("insurance_capital_adequacy",            "insurance", "Insurance: Capital Adequacy Ratio"),
    "4.5":      ("takaful_capital_adequacy",              "takaful",   "Takaful: Capital Adequacy Ratio"),
    "4.6":      ("life_insurance_new_business",           "insurance", "Life Insurance: New Business and Business in Force"),
    "4.6.1":    ("life_insurance_new_policies",           "insurance", "Life Insurance: No. of New Business Policies"),
    "4.6.2":    ("life_insurance_policies_inforce",       "insurance", "Life Insurance: No. of Policies in Force"),
    "4.6.3":    ("life_insurance_policies_terminated",    "insurance", "Life Insurance: No. of Policies Terminated"),
    "4.6.4":    ("life_insurance_new_business_premiums",  "insurance", "Life Insurance: Distribution of New Business Premiums"),
    "4.6.5":    ("life_insurance_premiums_inforce",       "insurance", "Life Insurance: Distribution of Annual Premiums in Force"),
    "4.6.6":    ("life_insurance_new_sums_insured",       "insurance", "Life Insurance: Distribution of New Sums Insured"),
    "4.6.7":    ("life_insurance_sums_insured_inforce",   "insurance", "Life Insurance: Distribution of Sums Insured in Force"),
    "4.6.8":    ("life_insurance_terminations_premiums",  "insurance", "Life Insurance: Terminations of Annual Premiums"),
    "4.6.9":    ("life_insurance_terminations_sums",      "insurance", "Life Insurance: Terminations of Sums Insured"),
    "4.6.a":    ("life_insurance_income_outgo",           "insurance", "Life Insurance: Income and Outgo"),
    "4.6.b":    ("life_insurance_fund_assets",            "insurance", "Life Insurance: Assets of Life Insurance Funds"),
    "4.7":      ("general_insurance_premium",             "insurance", "General Insurance: Premium Income"),
    "4.7.1":    ("general_insurance_direct_premiums",     "insurance", "General Insurance: Distribution of Gross Direct Premiums"),
    "4.7.2":    ("general_insurance_net_premiums",        "insurance", "General Insurance: Distribution of Net Premiums"),
    "4.7.3":    ("general_insurance_net_retention_combined","insurance","General Insurance: Combined Net Retention Ratio"),
    "4.7.4":    ("general_insurance_net_retention_direct","insurance", "General Insurance: Net Retention Ratio for Direct Insurers"),
    "4.7.5":    ("general_insurance_net_retention_reinsurers","insurance","General Insurance: Net Retention Ratio for Reinsurers"),
    "4.7.6":    ("general_insurance_reinsurance_premiums","insurance", "General Insurance: Reinsurance Position for Premiums Ceded"),
    "4.7.7":    ("general_insurance_reinsurance_claims",  "insurance", "General Insurance: Reinsurance Claims Recoveries"),
    "4.7.8":    ("general_insurance_reinsurance_commissions","insurance","General Insurance: Reinsurance Profit Commissions"),
    "4.7.9":    ("general_insurance_net_reinsurance",     "insurance", "General Insurance: Net Reinsurance Position"),
    "4.7.10":   ("general_insurance_claims_ratio_prev",   "insurance", "General Insurance: Claims Ratio"),
    "4.7.10.a": ("general_insurance_claims_ratio_direct", "insurance", "General Insurance: Claims Ratio for Direct Insurers"),
    "4.7.11":   ("general_insurance_professional_premiums","insurance","General Insurance: Reinsurance Accepted Premiums"),
    "4.7.12":   ("general_insurance_professional_net_premiums","insurance","General Insurance: Net Premiums for Professional Reinsurers"),
    "4.7.13":   ("general_insurance_professional_claims_ratio","insurance","General Insurance: Claims Ratio for Professional Reinsurers"),
    "4.7.14":   ("general_insurance_earned_premium",      "insurance", "General Insurance: Earned Premium Income"),
    "4.7.15":   ("general_insurance_gross_claims_direct", "insurance", "General Insurance: Gross Claims Paid for Direct Business"),
    "4.7.16":   ("general_insurance_gross_claims_reinsurance","insurance","General Insurance: Gross Claims Paid for Reinsurance Accepted"),
    "4.7.17":   ("general_insurance_claim_recoveries",    "insurance", "General Insurance: Claim Recoveries from Licensed Insurers"),
    "4.7.18":   ("general_insurance_claim_recoveries_foreign","insurance","General Insurance: Claim Recoveries from Foreign Insurers"),
    "4.7.19":   ("general_insurance_net_claims_paid",     "insurance", "General Insurance: Net Claims Paid"),
    "4.7.20":   ("general_insurance_net_claims_incurred", "insurance", "General Insurance: Net Claims Incurred"),
    "4.7.a":    ("general_insurance_underwriting_results","insurance", "General Insurance: Underwriting and Operating Results"),
    "4.7.b":    ("general_insurance_fund_assets",         "insurance", "General Insurance: Assets of General Insurance Funds"),
    "4.7.c":    ("general_insurance_technical_reserves",  "insurance", "General Insurance: Technical Reserves"),
    "4.8":      ("family_takaful_new_business",           "takaful",   "Family Takaful: New Business and Business in Force"),
    "4.8.1":    ("family_takaful_new_certificates",       "takaful",   "Family Takaful: No. of New Business Certificates"),
    "4.8.2":    ("family_takaful_sum_participated_new",   "takaful",   "Family Takaful: Distribution of Sum Participated of New Business"),
    "4.8.3":    ("family_takaful_new_contributions",      "takaful",   "Family Takaful: Distribution of New Business Contributions"),
    "4.8.4":    ("family_takaful_new_contributions_by_plan","takaful", "Family Takaful: Distribution of New Business Contributions by Plan"),
    "4.8.5":    ("family_takaful_certificates_inforce",   "takaful",   "Family Takaful: No. of Certificates In Force"),
    "4.8.6":    ("family_takaful_sum_participated_inforce","takaful",  "Family Takaful: Distribution of Sum Participated In Force"),
    "4.8.7":    ("family_takaful_annual_contributions_inforce","takaful","Family Takaful: Distribution of Annual Contributions In Force"),
    "4.8.8":    ("family_takaful_certificates_terminated","takaful",   "Family Takaful: No. of Certificates Terminated"),
    "4.8.9":    ("family_takaful_sum_participated_terminated","takaful","Family Takaful: Sum Participated of Terminated Certificates"),
    "4.8.10":   ("family_takaful_annual_contributions_terminated","takaful","Family Takaful: Annual Contributions of Terminated Certificates"),
    "4.8.a":    ("family_takaful_income_outgo",           "takaful",   "Family Takaful: Income and Outgo"),
    "4.8.b":    ("family_takaful_fund_assets",            "takaful",   "Family Takaful: Assets of Family Takaful Funds"),
    "4.8.c":    ("family_takaful_valuation_result",       "takaful",   "Family Takaful: Valuation Result"),
    "4.9":      ("general_takaful_gross_contributions",   "takaful",   "General Takaful: Distribution of Gross Contributions"),
    "4.9.1":    ("general_takaful_net_contributions",     "takaful",   "General Takaful: Distribution of Net Contributions"),
    "4.9.2":    ("general_takaful_domestic_retention",    "takaful",   "General Takaful: Domestic Retention"),
    "4.9.3":    ("general_takaful_gross_claims_paid",     "takaful",   "General Takaful: Gross Claims Paid"),
    "4.9.4":    ("general_takaful_net_claims_paid",       "takaful",   "General Takaful: Net Claims Paid"),
    "4.9.5":    ("general_takaful_claims_ratio",          "takaful",   "General Takaful: Claims Ratio"),
    "4.9.6":    ("general_takaful_earned_contributions",  "takaful",   "General Takaful: Earned Contribution Income"),
    "4.9.7":    ("general_takaful_net_claims_incurred",   "takaful",   "General Takaful: Net Claims Incurred"),
    "4.9.a":    ("general_takaful_underwriting_results",  "takaful",   "General Takaful: Underwriting and Operating Results"),
    "4.9.b":    ("general_takaful_fund_assets",           "takaful",   "General Takaful: Assets of General Takaful Funds"),
    "4.9.c":    ("general_takaful_technical_reserves",    "takaful",   "General Takaful: Technical Reserves"),
    "4.9.d":    ("general_takaful_contributions_income",  "takaful",   "General Takaful: Contributions Income"),
    "4.10":     ("insurance_key_indicators",              "insurance", "Insurance Key Indicators"),
    "4.10.1":   ("life_insurance_valuation_result",       "insurance", "Life Insurance Business: Valuation Result and Surplus Distribution"),
    "4.11":     ("takaful_key_indicators",                "takaful",   "Takaful Key Indicators"),
    "4.12":     ("insurance_broking_results",             "insurance", "Insurance Broking Business: Operating Results"),
    "4.12.1":   ("insurance_broking_premiums",            "insurance", "Insurance Broking Business: Total Premiums Transacted"),
    "4.13":     ("loss_adjusting_results",                "insurance", "Loss Adjusting Business: Operating Results"),
    "4.13.1":   ("loss_adjusting_cases",                  "insurance", "Loss Adjusting Business: Cases Handled by Adjusters"),
    # ── Section 5 ──────────────────────────────────────────────────────────────
    "5.1":      ("banking_institutions_list",             "banking",   "List of Banking Institutions"),
    "5.2":      ("leasing_factoring_assets_liab",         "other",     "Leasing and Factoring Companies: Statement of Assets and Liabilities"),
}


def table_name(table_id: str) -> str:
    """Convert table ID to DuckDB-safe table name: e.g. '1.3.1' → '1_3_1_broad_money_m3'"""
    norm_id = table_id.replace(".", "_")
    slug = CATALOG.get(table_id, (table_id.replace(".", "_"), "unknown", table_id))[0]
    return f"{norm_id}_{slug}"


def get_meta(table_id: str) -> dict:
    entry = CATALOG.get(table_id)
    if entry:
        slug, domain, title = entry
    else:
        slug, domain, title = table_id.replace(".", "_"), "unknown", table_id
    return {"table_id": table_id, "slug": slug, "domain": domain, "title": title,
            "table_name": table_name(table_id)}
